job_name: gpt35
random_seed: 69847

raw_dir: ../raw
processed_dir: processed
results_dir: results

qa_limit: 3 # Set to 0 to run all queries, otherwise only run this many (x2, presence and absence)
qa_batch_size: 100
qa_command: python3 ~/biodiversity-llms/scripts/nlp/qa.py
qa_args:
  - --max-tokens 1
  - --timeout 10
  - --num-responses 10
  - --combine_responses
qa_fields:
  - kingdom
  - phylum
  - family
  - genus
  - specificepithet
  - country
  - stateprovince
  - county
qa_base_queries:
  - Can species {genus} {specificepithet} be found in {county}, {stateprovince}, {country}?
  # - Is it possible to encounter species {3} {4} in {7}, {6}, {5}?
  # - Is there a presence of species {3} {4} within {7}, {6}, {5}?
  # - Does {7}, {6}, {5} harbor species {3} {4}?
  # - Is species {3} {4} present in {7}, {6}, {5}?
  # - Can one observe species {3} {4} in {7}, {6}, {5}?
qa_query_suffix: Only respond yes or no.