llm: gpt-4-1106-preview
random_seed: 69847
qa:
  occurrence:
    input: results/input/all-shuffled-69847.tsv
    shuffle: true
    query_limit: 40000
    batch_size: 100
  taxonomy:
    shuffle: false
    query_limit: 0
    batch_size: 100
results:
  notebook: results-gpt.py.ipynb
