llm: llama2-7b-chat
random_seed: 69847
qa:
  occurrence:
    shuffle: true
    query_limit: 0
    batch_size: 100
  taxonomy:
    shuffle: false
    query_limit: 0
    batch_size: 1000
results:
  notebook: results-llama2.py.ipynb
