llm: gpt-3.5-turbo-0613
random_seed: 69847
job_name: us-state-counties
qa:
  occurrence:
    input: results/idigbio-sample/input/maps/us-state-counties-acer-saccharum.tsv
    batch_size: 100
results:
  notebook: COMING-SOON.py.ipynb
